name: tts
dependencies:
    - python=3.10.0
    - pip
    - pip:
        - speechrecognition
        - simplejson
        - numpy
        - sounddevice
        - torch
        - librosa
        - datasets
        - transformers
        - vosk
        - espnet
        - espnet-model-zoo
        - espnet-tts-frontend
        - fairseq
        - zmq
        - pydantic==1.9.1