name: ailice
channels:
  - pytorch
  - defaults
dependencies:
    - python=3.10.0
    - pip
    - pip:
      - transformers>=4.0.0
      - torch
      - termcolor
      - scipy
      - peft
      - bitsandbytes
      - requests
      - docker
      - httpx==0.23.3
      - gradio
      - multiprocess
      - openai
      - pyparsing
      - pyyaml
      - zmq
      - regex
      - simplejson
      - protobuf
      - sentencepiece


