name: tts
dependencies:
    - python=3.10.0
    - pip
    - pip:
        - zmq
        - numpy
        - sounddevice
        - torch
        - torchaudio
        - librosa
        - transformers
        - espnet
        - espnet-model-zoo
        - espnet-tts-frontend