name: aservices
dependencies:
    - python=3.10.0
    - pip
    - pip:
        - transformers
        - torch
        - datasets
        - arxiv
        - requests
        - googlesearch-python
        - chromadb
        - urlextract
        - selenium
        - html2text
        - zmq
        - importlib-metadata